/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EstudiaRouteImport } from './routes/estudia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PortalEstudiantilRouteImport } from './routes/portal-estudiantil'
import { Route as PortalInformativoRouteImport } from './routes/portal-informativo'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as TerminosCondicionesRouteImport } from './routes/terminos-condiciones'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'
import { Route as TratamientoDatosRouteImport } from './routes/tratamiento-datos'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ProgramasIndexRouteImport } from './routes/programas/index'
import { Route as ProgramasSlugRouteImport } from './routes/programas/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminBlogNuevoRouteImport } from './routes/admin/blog/nuevo'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/admin/configuracion/index'
import { Route as AdminGaleriaIndexRouteImport } from './routes/admin/galeria/index'
import { Route as AdminInscripcionesIndexRouteImport } from './routes/admin/inscripciones/index'
import { Route as AdminMensajesIndexRouteImport } from './routes/admin/mensajes/index'
import { Route as AdminProgramasIndexRouteImport } from './routes/admin/programas/index'
import { Route as AdminProgramasIdRouteImport } from './routes/admin/programas/$id'
import { Route as AdminProgramasNuevoRouteImport } from './routes/admin/programas/nuevo'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin/usuarios/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiaRoute = EstudiaRouteImport.update({
  id: '/estudia',
  path: '/estudia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEstudiantilRoute = PortalEstudiantilRouteImport.update({
  id: '/portal-estudiantil',
  path: '/portal-estudiantil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInformativoRoute = PortalInformativoRouteImport.update({
  id: '/portal-informativo',
  path: '/portal-informativo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosCondicionesRoute = TerminosCondicionesRouteImport.update({
  id: '/terminos-condiciones',
  path: '/terminos-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientoDatosRoute = TratamientoDatosRouteImport.update({
  id: '/tratamiento-datos',
  path: '/tratamiento-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasIndexRoute = ProgramasIndexRouteImport.update({
  id: '/programas/',
  path: '/programas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasSlugRoute = ProgramasSlugRouteImport.update({
  id: '/programas/$slug',
  path: '/programas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNuevoRoute = AdminBlogNuevoRouteImport.update({
  id: '/admin/blog/nuevo',
  path: '/admin/blog/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/admin/configuracion/',
  path: '/admin/configuracion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGaleriaIndexRoute = AdminGaleriaIndexRouteImport.update({
  id: '/admin/galeria/',
  path: '/admin/galeria/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscripcionesIndexRoute = AdminInscripcionesIndexRouteImport.update({
  id: '/admin/inscripciones/',
  path: '/admin/inscripciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMensajesIndexRoute = AdminMensajesIndexRouteImport.update({
  id: '/admin/mensajes/',
  path: '/admin/mensajes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramasIndexRoute = AdminProgramasIndexRouteImport.update({
  id: '/admin/programas/',
  path: '/admin/programas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramasIdRoute = AdminProgramasIdRouteImport.update({
  id: '/admin/programas/$id',
  path: '/admin/programas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramasNuevoRoute = AdminProgramasNuevoRouteImport.update({
  id: '/admin/programas/nuevo',
  path: '/admin/programas/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/admin/usuarios/',
  path: '/admin/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudia': typeof EstudiaRoute
  '/galeria': typeof GaleriaRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/portal-estudiantil': typeof PortalEstudiantilRoute
  '/portal-informativo': typeof PortalInformativoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/programas/': typeof ProgramasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/programas/$id': typeof AdminProgramasIdRoute
  '/admin/programas/nuevo': typeof AdminProgramasNuevoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/galeria/': typeof AdminGaleriaIndexRoute
  '/admin/inscripciones/': typeof AdminInscripcionesIndexRoute
  '/admin/mensajes/': typeof AdminMensajesIndexRoute
  '/admin/programas/': typeof AdminProgramasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudia': typeof EstudiaRoute
  '/galeria': typeof GaleriaRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/portal-estudiantil': typeof PortalEstudiantilRoute
  '/portal-informativo': typeof PortalInformativoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/programas': typeof ProgramasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/programas/$id': typeof AdminProgramasIdRoute
  '/admin/programas/nuevo': typeof AdminProgramasNuevoRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/configuracion': typeof AdminConfiguracionIndexRoute
  '/admin/galeria': typeof AdminGaleriaIndexRoute
  '/admin/inscripciones': typeof AdminInscripcionesIndexRoute
  '/admin/mensajes': typeof AdminMensajesIndexRoute
  '/admin/programas': typeof AdminProgramasIndexRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/estudia': typeof EstudiaRoute
  '/galeria': typeof GaleriaRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/portal-estudiantil': typeof PortalEstudiantilRoute
  '/portal-informativo': typeof PortalInformativoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/terminos-condiciones': typeof TerminosCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/tratamiento-datos': typeof TratamientoDatosRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/programas/': typeof ProgramasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/programas/$id': typeof AdminProgramasIdRoute
  '/admin/programas/nuevo': typeof AdminProgramasNuevoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/galeria/': typeof AdminGaleriaIndexRoute
  '/admin/inscripciones/': typeof AdminInscripcionesIndexRoute
  '/admin/mensajes/': typeof AdminMensajesIndexRoute
  '/admin/programas/': typeof AdminProgramasIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/estudia'
    | '/galeria'
    | '/politica-privacidad'
    | '/portal-estudiantil'
    | '/portal-informativo'
    | '/quienes-somos'
    | '/terminos-condiciones'
    | '/trabaja-con-nosotros'
    | '/tratamiento-datos'
    | '/admin/login'
    | '/blog/$slug'
    | '/programas/$slug'
    | '/admin/'
    | '/blog/'
    | '/programas/'
    | '/admin/blog/$id'
    | '/admin/blog/nuevo'
    | '/admin/programas/$id'
    | '/admin/programas/nuevo'
    | '/admin/blog/'
    | '/admin/configuracion/'
    | '/admin/galeria/'
    | '/admin/inscripciones/'
    | '/admin/mensajes/'
    | '/admin/programas/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/estudia'
    | '/galeria'
    | '/politica-privacidad'
    | '/portal-estudiantil'
    | '/portal-informativo'
    | '/quienes-somos'
    | '/terminos-condiciones'
    | '/trabaja-con-nosotros'
    | '/tratamiento-datos'
    | '/admin/login'
    | '/blog/$slug'
    | '/programas/$slug'
    | '/admin'
    | '/blog'
    | '/programas'
    | '/admin/blog/$id'
    | '/admin/blog/nuevo'
    | '/admin/programas/$id'
    | '/admin/programas/nuevo'
    | '/admin/blog'
    | '/admin/configuracion'
    | '/admin/galeria'
    | '/admin/inscripciones'
    | '/admin/mensajes'
    | '/admin/programas'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/estudia'
    | '/galeria'
    | '/politica-privacidad'
    | '/portal-estudiantil'
    | '/portal-informativo'
    | '/quienes-somos'
    | '/terminos-condiciones'
    | '/trabaja-con-nosotros'
    | '/tratamiento-datos'
    | '/admin/login'
    | '/blog/$slug'
    | '/programas/$slug'
    | '/admin/'
    | '/blog/'
    | '/programas/'
    | '/admin/blog/$id'
    | '/admin/blog/nuevo'
    | '/admin/programas/$id'
    | '/admin/programas/nuevo'
    | '/admin/blog/'
    | '/admin/configuracion/'
    | '/admin/galeria/'
    | '/admin/inscripciones/'
    | '/admin/mensajes/'
    | '/admin/programas/'
    | '/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EstudiaRoute: typeof EstudiaRoute
  GaleriaRoute: typeof GaleriaRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  PortalEstudiantilRoute: typeof PortalEstudiantilRoute
  PortalInformativoRoute: typeof PortalInformativoRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  TerminosCondicionesRoute: typeof TerminosCondicionesRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
  TratamientoDatosRoute: typeof TratamientoDatosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProgramasSlugRoute: typeof ProgramasSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProgramasIndexRoute: typeof ProgramasIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNuevoRoute: typeof AdminBlogNuevoRoute
  AdminProgramasIdRoute: typeof AdminProgramasIdRoute
  AdminProgramasNuevoRoute: typeof AdminProgramasNuevoRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
  AdminGaleriaIndexRoute: typeof AdminGaleriaIndexRoute
  AdminInscripcionesIndexRoute: typeof AdminInscripcionesIndexRoute
  AdminMensajesIndexRoute: typeof AdminMensajesIndexRoute
  AdminProgramasIndexRoute: typeof AdminProgramasIndexRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudia': {
      id: '/estudia'
      path: '/estudia'
      fullPath: '/estudia'
      preLoaderRoute: typeof EstudiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-estudiantil': {
      id: '/portal-estudiantil'
      path: '/portal-estudiantil'
      fullPath: '/portal-estudiantil'
      preLoaderRoute: typeof PortalEstudiantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-informativo': {
      id: '/portal-informativo'
      path: '/portal-informativo'
      fullPath: '/portal-informativo'
      preLoaderRoute: typeof PortalInformativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-condiciones': {
      id: '/terminos-condiciones'
      path: '/terminos-condiciones'
      fullPath: '/terminos-condiciones'
      preLoaderRoute: typeof TerminosCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamiento-datos': {
      id: '/tratamiento-datos'
      path: '/tratamiento-datos'
      fullPath: '/tratamiento-datos'
      preLoaderRoute: typeof TratamientoDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/': {
      id: '/programas/'
      path: '/programas'
      fullPath: '/programas/'
      preLoaderRoute: typeof ProgramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$slug': {
      id: '/programas/$slug'
      path: '/programas/$slug'
      fullPath: '/programas/$slug'
      preLoaderRoute: typeof ProgramasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/nuevo': {
      id: '/admin/blog/nuevo'
      path: '/admin/blog/nuevo'
      fullPath: '/admin/blog/nuevo'
      preLoaderRoute: typeof AdminBlogNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion/': {
      id: '/admin/configuracion/'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/galeria/': {
      id: '/admin/galeria/'
      path: '/admin/galeria'
      fullPath: '/admin/galeria/'
      preLoaderRoute: typeof AdminGaleriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscripciones/': {
      id: '/admin/inscripciones/'
      path: '/admin/inscripciones'
      fullPath: '/admin/inscripciones/'
      preLoaderRoute: typeof AdminInscripcionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensajes/': {
      id: '/admin/mensajes/'
      path: '/admin/mensajes'
      fullPath: '/admin/mensajes/'
      preLoaderRoute: typeof AdminMensajesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programas/': {
      id: '/admin/programas/'
      path: '/admin/programas'
      fullPath: '/admin/programas/'
      preLoaderRoute: typeof AdminProgramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programas/$id': {
      id: '/admin/programas/$id'
      path: '/admin/programas/$id'
      fullPath: '/admin/programas/$id'
      preLoaderRoute: typeof AdminProgramasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programas/nuevo': {
      id: '/admin/programas/nuevo'
      path: '/admin/programas/nuevo'
      fullPath: '/admin/programas/nuevo'
      preLoaderRoute: typeof AdminProgramasNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EstudiaRoute: EstudiaRoute,
  GaleriaRoute: GaleriaRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  PortalEstudiantilRoute: PortalEstudiantilRoute,
  PortalInformativoRoute: PortalInformativoRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  TerminosCondicionesRoute: TerminosCondicionesRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
  TratamientoDatosRoute: TratamientoDatosRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProgramasSlugRoute: ProgramasSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProgramasIndexRoute: ProgramasIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNuevoRoute: AdminBlogNuevoRoute,
  AdminProgramasIdRoute: AdminProgramasIdRoute,
  AdminProgramasNuevoRoute: AdminProgramasNuevoRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
  AdminGaleriaIndexRoute: AdminGaleriaIndexRoute,
  AdminInscripcionesIndexRoute: AdminInscripcionesIndexRoute,
  AdminMensajesIndexRoute: AdminMensajesIndexRoute,
  AdminProgramasIndexRoute: AdminProgramasIndexRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
